fint:
  kafka:
    topic:
      org-id: 'ofk-no'
      domain-context: altinn
    application-id: ${fint.application-id}
    default-replicas: 1
spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}