fint:
  kafka:
    topic:
      #org-id: ${fint.org-id}
      domain-context: drosje
    application-id: ${fint.application-id}
spring:
  kafka:
    consumer:
      group-id: ${fint.org-id}-${fint.application-id}
