fint:
  kafka:
    topic:
      altinn-instance-created: bfk-no.altinn.event.instance-received

spring:
  kafka:
    properties:
        security.protocol: SSL
    admin:
      enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer