fint:
  org-id: ofk.no
  county-organization-number: 930580783 # Akershus
  county-number: 31
  altinn:
    ebevis:
      api:
        base-url: http://localhost:8080
server:
  port: 8083
logging:
  level:
    no.fintlabs.sourceapplicationInstanceController: DEBUG
spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
  datasource:
    hikari:
      schema: fintlabs_no
    url: jdbc:postgresql://localhost:5433/arkiv
    username: postgres
    password: postgres