spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${fint.database.url}
    username: ${fint.database.username}
    password: ${fint.database.password}
    hikari:
      schema: ${fint.database.username}