fint:
  org-id: fintlabs.no
server:
  port: 8083
logging:
  level:
    no.fintlabs.sourceapplicationInstanceController: DEBUG
spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
  datasource:
    hikari:
      schema: fintlabs_no
    url: jdbc:postgresql://localhost:5432/arkiv
    username: postgres
    password: postgres