fint:
  kafka:
    topic:
      org-id: fintlabs-no
      domain-context: drosje
    application-id: ${fint.application-id}
spring:
  kafka:
    consumer:
      group-id: fintlabs-no-${fint.application-id}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer