CREATE TABLE files
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_type    VARCHAR(255)                            NOT NULL,
    url          VARCHAR(255)                            NOT NULL,
    content_type VARCHAR(255),
    file_name    VARCHAR(255),
    instance_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_files PRIMARY KEY (id)
);

ALTER TABLE files
    ADD CONSTRAINT FK_FILES_ON_INSTANCE FOREIGN KEY (instance_id) REFERENCES instance (id);

ALTER TABLE instance
    ALTER COLUMN fint_org_id SET NOT NULL;

ALTER TABLE instance
    ALTER COLUMN instance_id SET NOT NULL;
