apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-altinn-service
  namespace: default
  labels:
    app.kubernetes.io/name: fint-altinn-service
    app.kubernetes.io/instance: fint-altinn-service
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-drosjesentral
    fintlabs.no/team: arkiv
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-altinn-service:sha-0000000
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  database:
    database: arkiv
  url:
    hostname: altinn.novari.no
    basePath: "/api"
  ingress:
    enabled: true
    basePath: path
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
  onePassword:
    itemPath: 'vaults/aks-beta-vault/items/altinn-service'
  resources:
    limits:
      memory: "2048Mi"
      cpu: "1"
    requests:
      memory: "512Mi"
      cpu: "100m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
