apiVersion: v1
kind: Service
metadata:
  name: fint-altinn-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  selector:
    app: fint-altinn-service
  type: LoadBalancer
  ports:
    - port: 8080