apiVersion: v1
kind: Service
metadata:
  name: fint-altinn-service
spec:
  selector:
    app: fint-altinn-service
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http